replicaCount: 2

image:
  repository: veshukla/hello-world
  tag: 12307afc7d02918da2d96f26b5bba3c5792f72ec
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
